### PR TITLE
Updated docs to include working with UC volumes

### PR DESCRIPTION
**Pull request by krishanunandy**

### CODE REVIEW

**Comment by dmoore247** [comment]
@krishanunandy Thank you for the contribution, a few items before approving...
1. Please sign the CLA, @dbbnicole that's required, right?
2. Please advise user in README update to use /Volumes/... (what you learned in your experience, and also what type of cluster). Thanks much!

**Comment by krishanunandy** [comment]
@dmoore247 I have -
1. Signed the CLA
2. Update the `README` based on your suggestions

Please let me know if you want me to make any other changes. (Also, apologies for the late reply - I didn't get a notification from Github that you'd left me a comment).

**Comment by dmoore247** [comment]
@krishanunandy The reason the integration tests failed is that the fork came from your Repo instead of a branch in this Repo. Something to keep in mind for future PRs. cc: @ramgoli-db

**Comment by dmoore247** [comment]
@krishanunandy There is a diagram error in the readme...
image

**Comment by krishanunandy** [comment]
@dmoore247 

> @krishanunandy The reason the integration tests failed is that the fork came from your Repo instead of a branch in this Repo. Something to keep in mind for future PRs. cc: @ramgoli-db
Good to know. In the past I had to create my own fork for contributing to Databricks Labs since only a small number of folks were given direct access to the repo.

> There is a diagram error in the readme...
I'm not sure what's going on here since it renders fine in VSCode.
image
It might be something to do with [Github's version of mermaid](https://github.com/mermaid-js/mermaid/issues/4388) but I'll have to do some more digging.

**Review by dmoore247 — APPROVED** [review]
Removed the mermaid designation from the code block

**Pull request merged**
